#!/usr/bin/expect -f
set timeout -1
spawn rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 65002" .next/standalone/ u549656247@82.29.157.55:domains/sextoyslovers.com/nodejs/
expect "password:"
send "Sathvika@2020\r"
expect eof

spawn rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 65002" .next/static/ u549656247@82.29.157.55:domains/sextoyslovers.com/nodejs/.next/static/
expect "password:"
send "Sathvika@2020\r"
expect eof
